import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",
  secondary: "0F172A",
  text: "334155",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
};

export const generatePpt = async (data) => {
  const ppt = new pptxgen();

  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "CortexAI";
  ppt.company = "CortexAI";
  ppt.subject = data.title;
  ppt.title = data.title;

  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };

  addCover(ppt, data);

  data.slides.forEach((slideData, index) => {
    addContentSlide(
      ppt,
      slideData.title,
      slideData.points,
      index + 1,
      data.slides.length
    );
  });

  addThankYou(ppt);

  return ppt;
};

function addCover(ppt, data) {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.primary,
  };

  slide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.333,
    h: 0.18,
    fill: { color: "60A5FA" },
    line: { color: "60A5FA" },
  });

  slide.addText(data.title, {
    x: 0.7,
    y: 1.7,
    w: 12,
    h: 0.7,
    align: "center",
    bold: true,
    fontSize: 28,
    color: COLORS.white,
  });

  slide.addText(data.subtitle || "", {
    x: 1,
    y: 2.7,
    w: 11.3,
    h: 0.5,
    align: "center",
    fontSize: 16,
    color: "DBEAFE",
  });

  slide.addText("Generated by CortexAI", {
    x: 0,
    y: 6.9,
    w: 13.333,
    h: 0.2,
    align: "center",
    fontSize: 10,
    color: "BFDBFE",
  });
}

function addContentSlide(ppt, title, points, page, total) {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.white,
  };

  slide.addText(title, {
    x: 0.6,
    y: 0.35,
    w: 11,
    h: 0.4,
    fontSize: 24,
    bold: true,
    color: COLORS.primary,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 0.6,
    y: 0.85,
    w: 12,
    h: 0,
    line: {
      color: COLORS.border,
      width: 1,
    },
  });

  const visiblePoints = (points || []).slice(0, 6);

  visiblePoints.forEach((point, index) => {
    const y = 1.2 + index * 0.75;

    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.7,
      y,
      w: 12,
      h: 0.55,
      fill: {
        color: index % 2 === 0 ? "EFF6FF" : "F8FAFC",
      },
      line: {
        color: COLORS.border,
      },
    });

    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.9,
      y: y + 0.18,
      w: 0.12,
      h: 0.12,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });

    slide.addText(point, {
      x: 1.15,
      y: y + 0.08,
      w: 11,
      h: 0.3,
      fontSize: 15,
      color: COLORS.text,
      fit: "shrink",
    });
  });

  slide.addText(`CortexAI`, {
    x: 0.6,
    y: 6.9,
    w: 2,
    h: 0.2,
    fontSize: 10,
    color: COLORS.muted,
  });

  slide.addText(`${page}/${total}`, {
    x: 12,
    y: 6.9,
    w: 0.8,
    h: 0.2,
    align: "right",
    fontSize: 10,
    color: COLORS.muted,
  });
}

function addThankYou(ppt) {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.secondary,
  };

  slide.addText("Thank You", {
    x: 0,
    y: 2.3,
    w: 13.333,
    h: 0.8,
    align: "center",
    bold: true,
    fontSize: 34,
    color: COLORS.white,
  });

  slide.addText("Generated by CortexAI", {
    x: 0,
    y: 6.9,
    w: 13.333,
    h: 0.2,
    align: "center",
    fontSize: 10,
    color: "94A3B8",
  });
}